/// Flutter icons TFoods
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TFoods
///      fonts:
///       - asset: fonts/TFoods.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TFoods {
  TFoods._();

  static const _kFontFam = 'TFoods';

  static const IconData tfoodstologotest = const IconData(0xe800, fontFamily: _kFontFam);
}
